<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dluyx2qsq/image/upload/v1554393070/DSC_4223.jpg" alt="Dayisi Iyanu">
                        <h6>Dayisi Iyanu</h6>
                        <p>Web Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/IyTobisin" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Thobeats" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://thobeatsidea.blogspot.com/" target="_blank"<i class="fab fa-Blogger fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, I'm Dayisi Iyanuoluwa, a web developer</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | HTML | Python | CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
