<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dya3r9cfe/image/upload/v1554313733/mypic.jpg" alt="Ugo P. Anayo">
                        <h6>Ugo P. Anayo</h6>
                        <p>Fullstack Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/KingUGGO" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/UggoPrince" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="http://medium.com/@uggoprince" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>
                            I love coding and developing software products.<br/>
                            And a critical thinker with B.Tech in Mathematics.<br/>
                            When I'm not coding I am either reading about Astronomy or Listening to gospel songs.
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | Java</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
