<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/abonzone/image/upload/v1554374789/cfd91f6f-d08e-4426-bee3-e7124e45e68e_1.png" alt="Mark Essien">
                        <h6>Abubakar A. Abubakar</h6>
                        <p>FullStack Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/SilentCoder92" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Bashabil" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am an Aspiring fullstack engineer, with intermediate experience on HTML, CSS and Javascript and also a beginner/intermediate experience with PHP and Javascript frameworks like Node.js, React and React-Native.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Node | PHP | React</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
