<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dfky4apck/image/upload/v1554381965/WhatsApp_Image_2019-03-28_at_4.51.51_PM_1.jpg" alt="Mark Essien">
                        <h6>Aliyu Israel Adavize</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/AdavizeTheFirst" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/AdavizeTheFirst" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://adavizethefirst.blogspot.com" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a tech Enthusiast, I do back end developnent, Desktop and front end too. I am also a student of The University of Lagos studying Computer Engineering.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Node Js | Electron Js | VB.net</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
