<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/praise/image/upload/v1554309081/samples/Me.jpg" alt="Anene Praise">
                        <h6>Anene Praise</h6>
                        <p>Software Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/A__Praise__" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Praise25" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@anenepraise1" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>My name is Anene Praise and I am a student of the University of Lagos. I am currently in my 2nd year and I am studying Computer science. I’m still basically a newbie to programming as I don’t really have projects that I’ve built but I’m well on my way.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
