<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/jocheattahdavid/image/upload/v1554369885/12BD001941_-_Copy.jpg" alt="Attah David">
                        <h6>Attah David</h6>
                        <p>Front-end Engineer & UI/UX Designer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/AttahIO" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/JocheAttah" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@jocheattahdavid" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Attah David is a front-end Developer and UI / UX Designer with a great love for his Job. I am currently an Intern at the HNG interships. I have a big heart for code and design; a 6th foot 4 helper for things on the high shelf.</p>
                        <br/>
                        <h6>Skills</h6>
                        <p>JavaScript | UI/UX | Photography</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
