<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/bilard/image/upload/v1554325942/WP_20160625_001.jpg" alt="Mark Essien">
                        <h6>Osinulu Adebayo</h6>
                        <p>Back-End Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/bilardyungmoney" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/captbilard" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@bilardosinulu" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, I am Adebayo Osinulu, a self-taught back-end developer, PluralSight certified JavaScript developer aspiring to become a Full Stack Web developer. I enjoy working with Python using Flask & Django framework, currently learning React JS to enhance my skills and create awesome user interfaces. Welcome to my world.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Python | JavaScript | CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
