<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/ddsgsyo4l/image/upload/v1554387337/fcd55fe4-a483-49ef-af3e-d122c5e000f0.jpg" alt="Jokotade Adewale">
                        <h6>Jokotade Adewale</h6>
                        <p>UI/UX Designer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/princess_tade" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Jokotade" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@princesstade007" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Am a Designer with passion for ui/ux design,i live in lagos. I like to design userfriendly product.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Figma | Adobe XD | InvisionApp</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
