<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/cafedeluv/image/upload/v1554418472/Personal/IMG_20180427_153048_574.jpg" alt="Olalekan Ajadi">
                        <h6>Olalekan Ajadi</h6>
                        <p>Front-end Web Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/cafedeluv" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/cafedeluv" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am an ardent lover of Information Technology. My love for Information Technology birthed a hungry drive for Software Development in me. I stumbled on Software Development during my personal study on Information Technology.  My discovery made me search frantically for opportunities that would groom my hungry drive to maturity.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML5 | CSS3 | Windows Administration</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
