<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dx6ol2ale/image/upload/v1554308671/me_44.jpg" alt="Charles Dim">
                        <h6>Charles Dim</h6>
                        <p>UI/UX Designer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/buikedim" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/buikedim" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@charlesdim" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a design enthusiast interested in making products more human centered. I've worked with Oluaka Institute and Oyapark. Currently i'm undergoing internship on the hotels.ng platform.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Bootstrap | Figma | CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
