<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/daviluiz/image/upload/v1554382113/Photo_on_13-02-2019_at_5.jpg" alt="Alfred Chimereze">
                        <h6>Alfred Chimereze</h6>
                        <p>FullStack Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/IkennaAlfred" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/AlfredBryan" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@alfred.chimereze" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, Am a fullstack web developer, with my main skills based on javaScript, always looking forward to more code challenges</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | React.js | Node.js</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
