<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dhmeafdra/image/upload/v1554337862/friends001.png" alt="Chimdike Nnacheta">
                        <h6>Chimdike Nnacheta</h6>
                        <p>Fullstack Android Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Sleek_Noah" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Sleeknoah" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@chimdikennacheta" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Passionate about what I do. I am a code lover, lover of sleek material design concepts and love to think outside the box. I am fun to be with especially as I can crack practical jokes. I love people and love to help them when I can. I love God.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Java | PHP | C++</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
