<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/cole/image/upload/v1554356214/Uploads/612e2dd8-73fd-4907-92b1-c8672b7f86d9.jpg" alt="Emeruche Cole">
                        <h6>Emeruche "Cole" Ikenna</h6>
                        <p>Fullstack Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/cole_ruche" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/kingingcole" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@emeruchecole9" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a self-taught fullstack web developer - with preference to front end. <br/>I love React JS and I love the web. <br/> I love Medium and I love Twitter.
                         <br/><br/>And <i>hey!</i> I'm a bespectacled medical student too!</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | React | Python (Django) </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
