<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/prince-curie/image/upload/c_crop,x_01,y_01/v1519776859/rsz_img_20180116_121815_wqutel_dovfsy.jpg" alt="image of Onwubiko Chibuike">
                        <h6>Onwubiko Chibuike</h6>
                        <p>Software Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Thisischibuike" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/prince-curie" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@princechibuike" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A budding software developer, 
                        loves learning and building things. 
                        I write JavaScript and nodeJS. 
                        Will be glad to interact with you.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | CSS | nodeJS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
