<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dxfahgv9s/image/upload/v1554394375/dafom.jpg" alt="Mark Essien">
                        <h6>Chollom Dafom</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/dafomchollom" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Dafomchollom" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@ayomidechollom" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a very chilled and easy going person, i work very well with teams and i enjoy learning new things.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | UI/UX Designs | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
