<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dvvme3lfj/image/upload/v1554361333/12565015.jpg" alt="Mark Essien">
                        <h6>Oluwadamilola Akintomide</h6>
                        <p>Full stack Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/lola_tomide" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/damiakintomide" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@damiakintomide" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p> My name is Oluwadamilola Akintomide. I am software developer using the following the languages ; PHP,
                    JAVA SE, HTML & CSS , JAVASCRIPT, BOOTSTRAP; As an intern at the HNG internship 5, i am very excited to do great things      
                </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | JAVA SE </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
