<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/daniel0101/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,b_rgb:262c35/v1554309162/daniel-1_jspkqq.jpg" alt="Daniel Awujoola">
                        <h6>Daniel Awujoola</h6>
                        <p>Software Developer</p>
                        <ul class="list">
                           <li><a href="https://www.twitter.com/danielawujoola" target="_blank"><i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://www.github.com/daniel0101" target="_blank"><i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://www.medium.com/@danielawujoola" target="_blank"><i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a software developer with a passion to learn new stuffs, mostly use backend technologies like php to make cool stuffs on the web</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>