<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/enwankwo/image/upload/v1554310907/IMG_20181217_134058_8_2.jpg" alt="Emmanuel Nwankwo">
                        <h6>Emmanuel Nwankwo</h6>
                        <p>Back-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/EmmaNwankwom" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/emmanuelnwankwo" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@emmanuelnwankwom" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A freelancer developer with a keen passion for using software technology to provide solutions to life needs.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | C#(.Net)</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
