<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://i.imgur.com/T6wzU0E.jpg" alt="Enya Emmanuel">
                        <h6>Enya Emmanuel Ideba</h6>
                        <p>Mobile Engineer</p>
                        <ul class="list">
                           <li><a href="#" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hey there!
                           My name is Enya Emmanuel Ideba, am a tech enthusiasts with love for<br>
                           mobile development and Artificial Intelligence.<br>
                           I have skills in java,dart,kotlin and python programming languages.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Java | Dart | Kotlin</p>
                     </div>
                  </div>

                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        
                        <h6>Social Media</h6>
                        <a href=https://web.facebook.com/emmanuel.enya.12>FaceBook</a>  
                        <a href=https://twitter.com/enyason95>Twitter</a>  
                        <a href=https://github.com/enyason>Github</a>  
                     </div>
                  </div>

               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>