
<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/uchiha0/image/upload/v1554400473/OBANDE_ESA_PHOTOGRAPH.jpg" alt="Esa Obande">
                        <h6>Esa Obande</h6>
                        <p>Back end Developer</p>
                        <ul class="list">
			   <li><a href="https://twitter.com/import_Esa" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/uchiha0" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://bankai.home.blog" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A lover of all things Python [the language not the snake!], Civil Engineering (BSc), Nuclear Power Plant Engineering (MSc) and financial markets enthusiast.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Python|Excel|Powerpoint</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
