<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dkg4moddv/image/upload/v1554310747/download.jpg" alt="Folarin Olatunji">
                        <h6>Folarin Olatunji</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/iam_pHolarine" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/4larin" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@folarin.tunji98/timbu-com-d4dc2f79d4bd" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a Visual Designer interning interning at Hotels.ng. I specialize in illustrations, UI UX designs , interface designs and web development.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | HTML | CSS </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
