<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/phreecodes/image/upload/v1554324631/WhatsApp_Image_2019-03-30_at_1.07.35_AM.jpg" alt="Eyimenarolu Freedom">
                        <h6>Eyimenarolu Freedom</h6>
                        <p>Back-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://github.com/phreecodes" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/phreecodes" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@eyimenarolufreedom" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I'm a programmer and I build for the web. I'm a graduate of Urban and Regional planning from Auchi Polytechnic, Auchi, Edo state and I'm currently an hotels.ng intern</p>
                        <br />
                        <h6>Skills</h6>
                        <p>PHP | JavaScript | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
