<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/doblyrqlj/image/upload/v1554381587/personal/profile.jpg" alt="Mark Essien">
                        <h6>Gloria Ojukwu</h6>
                        <p>Full Stack Web Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/gloriaojuks" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/gloriaojuks" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@giftdfgr8" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a full stack web developer. I work with PHP, JavaScript, ReactJs and collaboration tools like Jira, Slack, Confluence. I have always been involved and enjoy Ajile method of Development. I am glad to be on this Internship with eagerness to learn and work</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript(Reacjs) | PHP( PHP Phalcon)| Agile Development(Jira, Slack, Confluence,git,github) </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
