<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/djlw6gdzw/image/upload/v1554402450/1f00d510-2f7e-4f6a-b162-d1bbf82dd2ef.jpg" alt="Mark Essien">
                        <h6>Ifeanyichukwu Amajuoyi</h6>
                        <p>Frontend Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/AmajuoyiIfeanyi" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Anyitechs" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@aifeanyi019" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A passionate Software Developer that is in love with Christ.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Ruby | Flutter | Boostrap |</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
