<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/ifihan/image/upload/v1554389509/Ifihan.jpg" alt="Ifihan">
                        <h6>Olusheye Ifihanagbara</h6>
                        <p>I am a front-end developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Olusheye_Ifihan" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Ifihanolusheye" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://ifihanblog.blogpost.com" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a Frontend developer and a systems engineer in the making. I also have ideas on Python and C#. I am also a fan of technology.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>C# | CSS | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
