<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dm6nbay0f/image/upload/v1554311068/Irene.jpg" alt="Irene Okafor">
                        <h6>Irene Okafor</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/okafor_irene" target="_blank"><i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Irene-24" target="_blank"><i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@okaforirenen" target="_blank"><i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hello everyone, welcome to my profile.</p>
                        <p>I’m a Front-End Developer based in Nigeria.</p>
                        <p>When I’m not coding or learning how to code, I enjoy reading novels,manga and watching anime.</p>

                        <p>I’d like to use this internship opportunity to build my skills to a higher level.
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | CSS | C#</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
