<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/easyakowe1/image/upload/c_scale,w_550/v1554393339/israel.jpg" alt="Israel Akowe">
                        <h6>Israel Akowe</h6>
                        <p>Software Developer</p>
                        <ul class="list">
                           <li><a href="#" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://www.github.com/easyakowe" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://www.medium.com/@israelakowe" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am passionate about creating consumer-driven applications that provides solutions to prominent issues in the African context. I also have a knack for data analysis and manipulation because its applications can bring about new ways of measuring consumer behavior and ultimately making better predictions.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>PHP | Python | Java</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
