<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dmhoy3zpj/image/upload/v1554401999/HNG%205%20Internship/jayekwere.jpg" alt="Jonathan Ekwere">
                        <h6>Jonathan Ekwere</h6>
                        <p>Aspiring Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/jayekwere" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/jayekwere" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@jonathanekwere95" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a Software developer keen on Self improvement. I love developing new relationships, solving problems and also to contribute to the growth of a business, learning on how to have a strong grasp of security principles and how they should apply in order to get a secured product.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | JAVASCRIPT</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
