<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/rasmed-publications/image/upload/v1554371212/MyProfile.jpg" alt="Ajeigbe John Oluwaseyi">
                        <h6>Ajeigbe John Oluwaseyi</h6>
                        <p>Fullstack Web Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/john_pels" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/John-pels" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@slimmjohn4bright" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a Full-stack web developer. I mainly work with PHP, HTML, CSS, Javascript and WordPress. 
I also work with graphics packages like Photoshop, Illustrator and other nice packages.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | Java</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
