<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="http://res.cloudinary.com/karrim4real/image/upload/v1554361620/karrim.jpg" alt="Akinyemi Taiwo">
                        <h6>Akinyemi Taiwo K</h6>
                        <p>Fullstack Developer [MERN]</p>
                         <ul class="list">
                       <li><a href="twitter.com/karrim-real" target="_blank"<i class="fab fa-twitter"></i></a></li>
                       <li><a href="https://github.com/Karrim-real" target="_blank"<i class="fab fa-github"></i></a></li>
                       <li><a href="https://medium.com/@karrim4real" target="_blank"<i class="fab fa-medium"></i></a></li>
                       </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Here there, I am Aspiring  Software Engineer , I walk towaard been a sucessful software advocate to preach the gospel of Technology and Community Developnmet</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | MERN</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
