<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/maxspane/image/upload/v1554386878/download.png" alt="Mark Essien">
                        <h6>Mohammed Adetunji</h6>
                        <p>Android Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Max_Spane" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/MaxSpane" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@mohammedadetunji3" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I’m a freelance Android App Developer with almost three years of experience living in Lagos, Nigeria. I love algorithm challenges, video games, and all things technology, and I hope to make a noticeable impact in the technology Industry.  I hope to be exposed to Machine Learning during this internship.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Java | Go | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
