<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
<?php include 'partials/header.php'; ?>

<body class=" pi">
   <?php include 'partials/navbar.php'; ?>
   <section class="main-section">
      <div class="container">
         <div class="row">
            <div class="col-md-12 col-sm-6 col-xs-12">
               <div class="col-md-6 col-xs-12">
                  <div class="intern-block border-blue">
                     <img src="https://res.cloudinary.com/bulc-ng/image/upload/c_crop,h_1125,q_auto:good,r_20,w_1125/v1532209809/Users/testsix/gallery/0.jpg" alt="Mark Essien">
                     <h6>Moore Dagogo Hart</h6>
                     <p>Full Stack Engineer</p>
                     <ul class="list">
                        <li><a href="https://twitter.com/mooredh_" target="_blank" <i class="fab fa-twitter fa-2x"></i></a></li>
                        <li><a href="https://github.com/mooredh" target="_blank" <i class="fab fa-github fa-2x"></i></a></li>
                        <li><a href="https://medium.com/@mooredh99" target="_blank" <i class="fab fa-medium fa-2x"></i></a></li>
                     </ul>
                  </div>
               </div>
               <div class="col-md-6 col-xs-12 align-items-center">
                  <div class="intern-bio border-blue">
                     <h6>About me</h6>
                     <p>I am a student of University of Lagos in my 4th year. I bring software solutions in anyway that I can</p>
                     <br />
                     <h6>Skills</h6>
                     <p>JavaScript | C++ | Python</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
      </div>
   </section>
</body>
<?php include 'partials/footer.php'; ?>

</html>