<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/nathyjegs/image/upload/v1554311643/nathyjegs.jpg" alt="Mark Essien">
                        <h6>Nathanael Bakare</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/nathyjegs" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/nathyjegs" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@nathanaelbakare" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6 style="margin-top:-10px;">About me</h6>
                        <p>Nathanael Bakare is an aspiring software developer, with about one year's experience using the JavaScript language to hone his skills. Nathanael is also a photographer and content writer with his works having been featured in a number of publications.</p>
                        <p style="margin-top:-4px;">Nathanael currently live in Lagos, Nigeria.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Content Writing | Photography</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
