<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/ikejiwilliam/image/upload/v1554329597/nonso_1.jpg" alt="Chukwunonso Ikeji">
                        <h6>Chukwunonso Ikeji</h6>
                        <p>Full stack web developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/tech_cruiser" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/iamwilliam19" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@williamikeji" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a tech enthusiast though currently studying pharmacy, I have been in the tech industry for about 18months now. My interests are basically web, android ,AI and automation. </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | SQL</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
