<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/notthattayo/image/upload/v1554318408/hng_profile.jpg" alt="Tayo Adegoke">
                        <h6>Omotayo Adegoke</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/NotThatTayo" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/notthattayo/" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@godzillaofthevilla" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a software developer based in Lagos state, Nigeria, and i create web applications using Html, css and javascript. I am 23 years old and I began my journey into web development in December 2018. It has been a great learning experience so far.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | HTML | CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
