<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/goldolar/image/upload/v1554316421/Olamide_Samuel.png" alt="Olamide Samuel">
                        <h6>Olamide Samuel</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/gold_olar" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/gold-olar" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://olamidesamuel.blogspot.com" target="_blank"<i class="fab fa-blogger fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a student, Obafemi Awolowo University. I enjoy learning on the go and impacting knowledge. I hope to be a full stack developer some day.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML 5| CSS 3 | NODEJS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
