<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dj9ywvcsj/image/upload/v1554356934/8b777e5d-d540-42e4-b3bd-923b8b69021b_1.jpg" alt="Olaniyi Ajayi">
                        <h6>Olaniyi Ajayi</h6>
                        <p>Data Scientist and Machine Learning Engineer</p>
                        <ul class="list">
                           <li><a href="https://www.linkedin.com/in/olaniyi-ajayi-7469ba4a/" target="_blank"<i class="fab fa-Linkedin fa-2x"></i></a></li>
                           <li><a href="https://github.com/Olaniyiajayi" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@ajayiolaniyi" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I love technology, especially Artificial Intelligence, and I love to impact in others </p>
                        <br />
                        <h6>Skills</h6>
                        <p>Python | Machine Learning</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>