<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/sirphemmiey/image/upload/c_scale,h_500,w_500/v1554329723/20180525110131_IMG_6495-v2_1_fcvvof.png" alt="Oluwafemi Akinde">
                        <h6>Oluwafemi Akinde</h6>
                        <p>Fullstack Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/oluwafemiakind1" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/sirphemmiey" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@oluwafemiakinde" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I love working on progressively challenging projects with/without team members; building amazing products from first principles and innovating from there on. I don't just develop software; I build real, scalable and sustainable solutions to real problems.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | Solidity</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
