<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/djcoxy666/image/upload/v1554322416/samples/6f2f1bcc-bff9-41e2-b173-a39cbf959571.png" alt="Omakoji Danlami Enejoh">
                        <h6>Omakoji Danlami Enejoh</h6>
                        <p>Fullstack Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/OmacodeG" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/ernestmoi" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@ernestmoi34" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am very passionate about making ideas come to reality. I am a Fullstack Software Engineer,i keeep to deadlines and i work great in teams. I also like the game of basketball.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | MySql</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
