<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/kenenna/image/upload/v1554313951/HNG_1.png" alt="Kenenna Onwuagba">
                        <h6>Kenenna Onwuagba</h6>
                        <p>Software Developer</p>
                        <ul class="list">
                           <li><a href="www.twitter.com/kenennacollins" target="_blank"><i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="www.github.com/Onwuagba" target="_blank"><i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@onwuagbakenenna" target="_blank"><i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>As the fastest means of product marketing is the web,Kene desires to help companies promote their products through the development and quality assurance of standard web apps. <br>
Kene can be described as one who is rather passionate about IT because of the solutions it provides regarding information and communication problems.
                        </p>
                        <br />
                        <h6>Skills</h6>
                        <p> PHP | Flutter | Python (Beginner)</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
