<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/onyiiee/image/upload/v1554379906/Slack%20name/20161010_085424_1.png" alt="Onyinye Okoye">
                        <h6>Onyinye Okoye</h6>
                        <p>Front end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Ms_Jny" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/onyiiee" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@onyinye.okoye34" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I'm a Frontend developer and an AI enthusiast. I transitioned from Food Science to Software development in 2018 and its been quite an interesting journey. I am working towards becoming an AI expert who would add value-driven solutions to systems. I love spa sessions and ice cream.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Machine Learning | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
