<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/sk8er/image/upload/v1554327710/30738604_616034378733752_8978504105790013440_n.jpg" alt="Mark Essien">
                        <h6>Patrick Odey</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/patrickodey360" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Patrickodey360coder" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@patrickodey984" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, I'm Patrick Odey. A front-end developer/tech junkie. I enjoy helping people progress. When I'm not coding, I play video games or skateboard</p>
                        <br />
                        <h6>Skills</h6>
                        <p>CSS | HTML | JavaScript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
