<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/zerubbabel/image/upload/v1554382751/my_pictures_IMG-20190105-WA0002-c_scale_h_512_w_512.jpg" alt="Popoola Boluwatife">
                        <h6>Popoola Boluwatife</h6>
                        <p>Back-end Engineer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Iam__Prometheus"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/ZerubbabelP"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@olaoyejnr"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am  a python developer, proficient in django and a Tech enthusiast, i love to learn, research and solve problems. profile wont be complete if i dont mention am a football fan. </p>
                        <br />
                        <h6>Skills</h6>
                        <p>Python |HTML | Django</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
