<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/roqeeb/image/upload/v1554332920/Webp.net-resizeimage.jpg" alt="Mahmud Roqeeb">
                        <h6>Mahmud Roqeeb</h6>
                        <p>Front-end web developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/Raeynique" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/Pholusho" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://raeyhub.wordpress.com" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About Me</h6>
                        <p>I am a front-end developer , and a database analyst , i am also a cyber security enthusiast, i would love to learn various types of JS, and server scripting languages.</p>
                        <br />
                        <h6>Skills</h6>
                        <p> HTML | CSS | SQL </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
