<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/skolapo/image/upload/v1554321563/Passport_photo.jpg" alt="Said Kolapo">
                        <h6>Said Kolapo</h6>
                        <p>Full Stack</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/s_Hotzs" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/skolapo" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I have exceptional sales and relationship building skills along with proven ability to learn new products, skills and tactics, adept at working to efficiently achieve organizational goals. And oh, I made transition to coding (Wed Development), currently writing “Hello World” codes in HTML, CSS and JavaScript</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | JavaScript</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
