<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/skylarng89/image/upload/v1554326702/hng5/Me2.jpg" alt="Patrick Aziken">
                        <h6>Patrick Aziken</h6>
                        <p>UI Designer, Web Design & Software Tester</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/skylarng89" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/skylarng89" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@skylarng89" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a creative individual. I love collaboratiing with others to get things done. My favourite tools for work include Figma, Avocode, VS Code and WAMP. To unwind, I play video games, watch Sci-Fi movies or listen to great music. I hope to become to Full Stack Software Developer someday.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | CSS | Automated & Manual Testing</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
