<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
<?php include 'partials/header.php'; ?>

<body class=" pi">
    <?php include 'partials/navbar.php'; ?>
    <section class="main-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-6 col-xs-12">
                    <div class="col-md-6 col-xs-12">
                        <div class="intern-block border-blue">
                            <img src="https://res.cloudinary.com/dyct7elf7/image/upload/v1554366112/dammy.jpg">
                            <h6>Damilola Shofoluwe</h6>
                            <p>Front-end Developer || UI/UX Designer</p>
                            <ul class="list">
                                <li><a href="https://twitter.com/MadeByDammy" target="_blank" <i
                                        class="fab fa-twitter fa-2x"></i></a></li>
                                <li><a href="https://github.com/ddamox" target="_blank" <i
                                        class="fab fa-github fa-2x"></i></a></li>
                                <li><a href="https://medium.com/@damilolashofoluwe01" target=" _blank" <i
                                        class="fab fa-medium fa-2x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12 align-items-center">
                        <div class="intern-bio border-blue">
                            <h6>About me</h6>
                            <p>I am a Frontend developer and ui/ux designer. I am addicted to css. I have worked with
                                css and javascript</p>
                            <br />
                            <h6>Skills</h6>
                            <p> CSS | FIGMA | ADOBE XD</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
</body>
<?php include 'partials/footer.php'; ?>

</html>