<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
<?php include 'partials/header.php'; ?>

<body class=" pi">
   <?php include 'partials/navbar.php'; ?>
   <section class="main-section">
      <div class="container">
         <div class="row">
            <div class="col-md-12 col-sm-6 col-xs-12">
               <div class="col-md-6 col-xs-12">
                  <div class="intern-block border-blue">
                     <img src="https://res.cloudinary.com/nonso/image/upload/v1554361647/StanleyNdunwere/StanleyNdunwere.png" alt="Stanley Ndunwere">
                     <h6>Stanley Ndunwere</h6>
                     <p>UI/UX and Backend Developer</p>
                     <ul class="list">
                        <li><a href="#" target="_blank" <i class="fab fa-twitter fa-2x"></i></a></li>
                        <li><a href="https://github.com/StanleyNdunwere/" target="_blank" <i class="fab fa-github fa-2x"></i></a></li>
                        <li><a href="https://medium.com/@stanleyndunwere" target="_blank" <i class="fab fa-medium fa-2x"></i></a></li>
                     </ul>
                  </div>
               </div>
               <div class="col-md-6 col-xs-12 align-items-center">
                  <div class="intern-bio border-blue">
                     <h6>About me</h6>
                     <p>Software development enthusiast with a soft spot for music. Strengths include overall software architecture design, UX/UI design and implementing iron-clad business logic in the backend.
                        Front-end skills covers HTML, CSS and Vanilla JS.
                        <br>
                        My superpower: Learning stuff fast, like speedster fast!
                     </p>
                     <br />
                     <h6>Skills</h6>
                     <p>PHP | HTML/CSS | (Vanilla) JS</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
      </div>
   </section>
</body>
<?php include 'partials/footer.php'; ?>

</html>