<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/taiwod/image/upload/v1554390758/20190401_104236_1.jpg" alt="Taiwo Osokoya">
                        <h6>Taiwo Osokoya</h6>
                        <p>UI/UX Designer</p>
                        <ul class="list">
                           <li><a href="https://github.com/Txiwo" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://twitter.com/TaiwoLare" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@taiwodamilare" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hi, My name is Taiwo. I'm a UI/UX Designer who is passionate about making usable products and solutions.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>Adobe XD | Figma | InVision Studio</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
