<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/theboringdude/image/upload/v1554390589/hng-photo.jpg" alt="Saviour Essien">
                        <h6>Saviour Essien</h6>
                        <p>Front-End Engineer</p>
                        <ul class="list">
                           <li><a href="https://facebook.com/the_boringdude" target="_blank"><i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/theboringdude" target="_blank"><i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@essiensaviour.a" target="_blank"><i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am from Akwa Ibom State, Nigeria. I am a Front End Developer by profession with 2 years of active working. Also, I am aspring to become a Full Stack JavaScript Developer. Currently, I serve as the Lead for GDG Yenagoa and forLoop Yenagoa. Building and shipping products gives me a lot of joy.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
