<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/dfpljttj3/image/upload/v1554369022/IMG_20190126_131307_7.jpg" alt="Adekanye Timilehin">
                        <h6>Adekanye Timilehin Micheal</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="#" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I'm a Frontend developer and Graphics designer. Student of Ladoke Akintola University of Technology. I love playing adventure games and finding out more about latest technologies.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | Javascript | CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
