<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/walebant/image/upload/v1554380548/wale_bant.jpg" alt="Ashiru Olawale">
                        <h6>Ashiru Olawale</h6>
                        <p>Front-end Web Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/wale_bant" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/wale-bant" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@wale_bant" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>I am a web development and tech enthusiast. I love the idea of creating great designs and making things work. I love reading about technology and learning new things.</p>
                        <br />
                        <h6>Skills</h6>
                        <p> HTML | CSS | Git</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
