<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
<?php include 'partials/header.php'; ?>

<body class=" pi">
    <?php include 'partials/navbar.php'; ?>
    <section class="main-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-6 col-xs-12">
                    <div class="col-md-6 col-xs-12">
                        <div class="intern-block border-blue">
                            <img src="https://res.cloudinary.com/ben-j/image/upload/v1554418986/IMG_20180517_0911152.jpg" alt="Uforo Ibenge">
                            <h6>Ibenge Uforo</h6>
                            <p>Front-end Engineer</p>
                            <ul class="list">
                                <li><a href="#" target="_blank" <i class="fab fa-twitter fa-2x"></i></a></li>
                                <li><a href="https://github.com/ibengeu" target="_blank" <i class="fab fa-github fa-2x"></i></a></li>
                                <li><a href="#" target="_blank" <i class="fab fa-medium fa-2x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12 align-items-center">
                        <div class="intern-bio border-blue">
                            <h6>About me</h6>
                            <p>Hi there,
                                My name is Uforo Ibenge , a student fascinated and passionate about creating solutions
                                to problems either by designing a solution with prototyping tools or using high level
                                languages in coming up with the identified solution. </p>
                            <br />
                            <h6>Skills</h6>
                            <p>UI/UX design | Javascipt | Python</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
</body>
<?php include 'partials/footer.php'; ?>

</html> 