<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
<?php include 'partials/header.php'; ?>

<body class=" pi">
    <?php include 'partials/navbar.php'; ?>
    <section class="main-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-6 col-xs-12">
                    <div class="col-md-6 col-xs-12">
                        <div class="intern-block border-blue">
                            <img src="https://res.cloudinary.com/di1qgpcry/image/upload/v1554368980/pix-me.jpg" alt="zaheer">
                            <h6>Simeon Bello</h6>
                            <p>Front-end Developer</p>
                            <ul class="list">
                                <li><a href="https://twitter.com/za_hyer" target="_blank" <i class="fab fa-twitter fa-2x"></i></a></li>
                                <li><a href="https://github.com/Seybel" target="_blank" <i class="fab fa-github fa-2x"></i></a></li>
                                <li><a href="https://medium.com/@seyibello31" target="_blank" <i class="fab fa-medium fa-2x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6 col-xs-12 align-items-center">
                        <div class="intern-bio border-blue">
                            <h6>About me</h6>
                            <p>I'm a front-end web developer interested in creating tech solutions. I also love doing back-end development with PHP and Mysql and i am hoping to extend that to Laravel as well.</p>
                            <br />
                            <h6>Skills</h6>
                            <p>JavaScript | PHP | Bootstrap</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
</body>
<?php include 'partials/footer.php'; ?>

</html>